A01 rcparse: Modify the public interface to be able to pass newphrases.
- The new interface is backwards compatible with the old one, with one
  exception: if the identifier "define_revision_ex" was used in a
  derived class, then most probably there will be a usage conflict and
  that derived class member will need to be renamed.